### ISSUE TITLE
Dependency injection does not dispose objects

### ISSUE THREAD

**Issue by TiruYasha** [Remiworks/EventBusFramework#11]
What the title says

**Comment by TiruYasha** [comment]
I found the problem... The AddDbContext extension methods has a Lifetime scope of Scoped.
https://github.com/aspnet/EntityFrameworkCore/blob/bf5e2c566c121065ff7a65890d68a265b035c512/src/EFCore/EntityFrameworkServiceCollectionExtensions.cs

To fix this use ".AddDbContext<PcsOnderhoudContext>(options =>
                    options.UseSqlServer(connectionString), **ServiceLifetime.Transient**)"

**Comment by mikederksen** [comment]
Are you sure that the startup is refreshed? I don't think this happens with MVC.

Couldn't it be that we retrieve the controller class in a wrong way from the service provider?

**Comment by TiruYasha** [comment]
Not necessary anymore
