### ISSUE TITLE
If the timeout expires delete command from the queue

### ISSUE THREAD

**Issue by TiruYasha** [Remiworks/EventBusFramework#12]

**Comment by TiruYasha** [comment]
Is this really necessary tho?

**Comment by mikederksen** [comment]
I think this is a good idea. If a command throws a timeout, it means that the calling party moves on and is not listening to a callback anymore. This will mean that their will either be unhandled commands in the queue or unhandled command callbacks in the callback queue

**Comment by mikederksen** [comment]
This situation will not be possible, since events cant reach a queue without a exchange bind on the corresponding topic. This exchange bind can only be done by the event listener, which in turn means that something is listening on the queue.
