### ISSUE TITLE
Events get lost when one listens to a queue, but not to all topics from that queue

### ISSUE THREAD

**Issue by mikederksen** [Remiworks/EventBusFramework#18]
Imagine that an application listens to the 'TestQueue' queue and to the topics 'Some.Thing1' and 'Some.Thing2'. When an event with topic 'Some.Thing3' comes in, the framework will pick up this event from the queue. Then it starts parsing the key to see if it has a matching topic listener somewhere. If it does not have a matching topic listener, nothing is called, but the event is gone from the queue.

This can be solve by disabling auto-acknowledge. When the framework finds a matching topic, it can acknowledge the event.

**Comment by TiruYasha** [comment]
Not an issue
